#+title: Glossaires et acronymes harmonisés
#+author: Free Engineering
#+date: <2025-02-28 Fri>
#+license: MIT

L'emplois d'un référenciel harmonisé des termes et définitions et d'acronymes permet d'assurer la cohérence d'ensemble de vos documents et d'opérer un alignement sémantique au sein de votre organisation et de vos projets. L'utilisation du présent glossaire vous assure d'employer des définitions faisant consencus dans la profession.

Pour l'utiliser automatiquement lors de la rédaction de vos document, nous vous conseillons d'utiliser le module d'extension d'Emacs : Org-Glossary.

Commencez par cloner le dépôt "FreeEngineering/charte-unique"
#+begin_src bash
git clone https://github.com/FreeEngineering/charte-unique.git ~/charte-unique
#+end_src

#+RESULTS:

Puis, dans votre fichier de configuration Emacs (généralement ~.emacs~ ou ~.init~) ajoutez le script suivant :
#+begin_src emacs-lisp
(use-package org-glossary
  :straight (:host github :repo "tecosaur/org-glossary"))
#+end_src

Remarquez que nous utilisions le gestionnaires de paquets ~straight.el~. Pour configurer Straight, [[https://github.com/radian-software/straight.el?tab=readme-ov-file#getting-started][suivez ce tutoriel]].

Pour imprimer les entrées lors de l'export LaTeX, vous pouvez utilisez les balises suivantes :
#+begin_src org-mode
#+print_bibliography:
#+print_bibliography: :type glossary
#+print_bibliography: :type acronyms
#+end_src

~#+print_glossary:~ Imprimera toutes les entrées trouvées dans votre document et organisera naturellement le glossaire, les acronymes et l'index.
~#+print_glossary: :type glossary~ Imprimera uniquement le glossaire. 
~#+print_glossary: :type acronyms~ Imprimera uniquement les acronymes. 

* Glossaire

* Acronymes
- DRAO :: Dossier reponse appel d'offre
- DCE :: Dossier de consultation des entreprises
- DEM :: Dossier d'exploitation et maintenance

Dossier des quallifications
- DQF :: Dossier de qualification foudre

- DSN :: Dossier de surete nucleaire
- DAU :: Dossier d'administration et d'utilisation

Dossiers des definitons
- DDF :: Dossiers des définitions foudres

- DJD :: Dossier de justification detaille
- DPL :: Dossier de programmation logiciel
- DSLI :: Dossier de soutiens logistique integre

Dossiers d'etude
- ETF :: Etude Technique Foudre
  
Dossier d'installation
- DFA :: Dossier de fabrication
- DOE :: Dossier des ouvrage execute
- DSF :: Dossier de sureté de fonctionnement
- DII :: Dossier d'identification des interfaces
- DOFC :: Dossier des outillages de fabrication et contrôle

- RCO :: Répertoire des configurations
- RDE :: Répertoire des dérogations
- REV :: Répertoire des évolutions
- RFQ :: Repertoire des fqr
- RNC :: Répertoire des non conformités


- 2D :: 2 Dimensions ::
- 2 Dimensions :: Une représentation 2D (ou bidimensionnelle) d’un élément consiste à représenter celui-ci en deux dimensions (généralement la longueur et la largeur).
- 3D :: 3 Dimensions
- 3 Dimensions :: Une représentation 3D (ou tridimensionnelle) d’un élément consiste à représenter celui-ci en trois dimensions (la longueur, la largeur et la hauteur). Cet élément peut donc être observé dans l’espace, depuis n’importe quel angle de vue.
- ACQ :: Activités Concernées par la Qualité	
- AIA :: American Institute of Architecture
- American Institute of Architecture :: Organisation professionnelle d'architectes américains des États-Unis
- ACV :: Analyse du Cycle de Vie
- Analyse du Cycle de Vie :: Méthodologie multicritère d’évaluation environnementale, normalisée ISO 14040-44.
- ATS :: Applicant Tracking System
  :: Logiciel de gestion des candidatures ; Outil destiné aux recruteurs qui permet de centraliser toutes les données liées au recrutement et d'administrer ses campagnes de recrutement depuis un outil unique.
- API :: Application Programming Interface
  :: Bibliothèque de programmation pour piloter un logiciel depuis une application logicielle tiers.
- ARC :: Architecture
  :: Art de construire les bâtiments.
- AEC :: Architecture Engineering and Construction	
- APE :: Armoire à plans électronique
  :: Système informatique de contrôle de plans numérisés pour les opérations de synthèses. La gestion porte sur les entités du cartouche, non sur le contenu.
- AC :: Article de Configuration
- ACSN :: Article de Configuration de Sureté Nucléaire	
- AIM :: Asset Information Model
- AIR :: Asset Information Requirements
  :: Exigences d’informations de l’actif.Sont générées à partir de l’OIR et contribuent à la spécification de l’EIR.
- AMO :: Assistant de Maître d’Ouvrage
  :: Rôle qui consiste à assister le maître d’ouvrage en se chargeant de certaines ou de l’ensemble des tâches liées au projet (au nom et pour le compte du maître d’ouvrage).
- AFNOR :: Association Française de Normalisation
  :: Organisation française qui représente la France auprès de l'Organisation internationale de normalisation et du Comité européen de normalisation.
- Attribut :: Description associée uniquement à un objet
- AR :: Augmented Reality
  :: La réalité augmentée (augmented reality) désigne les systèmes informatiques qui rendent possible la superposition d’un modèle virtuel 3D ou 2D à la perception que nous avons naturellement de la réalité et ceci en temps réel.
- ASN :: Autorité de Sureté Nucléaire
- ASND :: Autorité de Sureté Nucléaire Défense
- APD :: Avant Projet Définitif
- APS :: Avant Projet Sommaire
  :: Phase d’exploration des différentes solutions possibles. Durant cette étape, les équipes s’intéressent d’avantages à la fonctionnalité.
- AVP :: Avant-Projet
  :: Regroupement des phases APS et APD généralement réalisé dans le secteur privé pour raccourcir le temps de conceptualisation du projet.
- BDD :: Base De Données
  :: Système d'organisation de données englobant la structure d'information, l'information numérisée elle-même (fichiers) et les procédures ou langage d'accès.On entend par base de données un recueil d'œuvres, de données ou d'autres éléments indépendants, disposés de manière systématique ou méthodique, et individuellement accessibles par des moyens électroniques ou par tout autre moyen (Code de la Propriété Intellectuelle L112-3, 2ème alinéa).
- BOQ :: Bill Of Quantity	
- BIM 4D :: Usage BIM dans lequel des données de planiﬁcation sont associées à certains éléments du modèle BIM.Le planning est ainsi intégré au sein du modèle et on peut le visualiser sous une perspective séquentielle, mais aussi réaliser diverses analyses concernant les délais.
- BIM 5D :: Usage BIM dans lequel les éléments, les types ou les matériaux du modèle BIM sont reliés à une base de données de coûts.Cette liaison peut s’opérer par l’intermédiaire de codes de coût, ce qui permet de procéder à une estimation intégrée des coûts.
- BCF :: Bim Collaboration Format
  :: Standard ouvert de buildingSMART qui facilite la communication par l’intermédiaire du modèle numérique au cours du projet.Il permet de transmettre des remarques ou des demandes de modiﬁcation sans devoir échanger l’ensemble du modèle numérique.Un ﬁchier BCF comprend entre autres une capture d’écran, la position de la caméra, des commentaires, l’assignation des commentaires aux personnes concernées ainsi qu’une liste des éléments associés.
- BIM Manager :: Rôle BIM qui consiste à diriger le processus BIM global, en vue de son bon déroulement, et à assister l’équipe de projet.
- BIM Modeleur :: C’est un projeteur expert en modélisation 3D et en gestion de l’information.Son rôle et son périmètre d’intervention sont avant tout productifs.Suivant les recommandations et prescriptions établies par le BIM management, il élabore, modélise les ouvrages, produit et édite les modèles 3D, les plans nécessaires à chaque phase du projet…Il peut réaliser aussi des contributions d’autres natures (notes de calculs, qualifications des données, spécification des nomenclatures, etc.), qui peuvent constituer des données de la maquette.
- BIM XD :: Au-delà de 5D, on généralise aux autres informations qui peuvent être ajoutées aux objets BIM, comme l'acoustique, l'impact environnemental, la thermique...
- BIM-Catalogue :: Catalogue d’objets sous format numérique intégrables dans une maquette numérique. Un BIM-catalogue peut être générique ou spécifique à un fournisseur.
- BrIM :: Bridge Information Modeling
  :: Equivalent du BIM pour les ouvrages d’arts.
- BEM :: Building Energy Modeling
  :: Modélisation Energétique du Bâtiment
- BIM :: Building Information Modeling
  :: Ensemble de méthodologies de travails, lié au secteur du bâtiment, utilisant un support de données unifiées au moyen d'une maquette numérique.Selon NF EN ISO 19650 : utilisation d’une représentation numérique partagée d’un actif bâti pour faciliter les processus de conception, de construction et d’exploitation de manière à constituer une base fiable permettant les prises de décision.
- bSDD :: buildingSMART Data Dictionary
  :: Format et système de base de données pour recenser, de manière internationale, les propriétés des objets BIM.
- bSI :: buildingSMART Internationnal
  :: Association internationale (anciennement l’IAI), regroupant des entreprises du secteur de la construction et des éditeurs de logiciels. Cette organisation est divisée en chapitres nationaux dont Mediaconstruct est le représentant français. Elle a pour objectif principal de favoriser l’interopérabilité des logiciels dans le secteur de la construction.
- BPMN :: Business Process Model and Notation
  :: Norme de modélisation des processus métier en français, est une méthode de logigramme qui modélise de A à Z les étapes d'un processus métier planifié. Elle constitue la norme internationale ISO/CEI 19510
- CDC :: Cahier Des Charges
  :: Document du maître d’ouvrage qui précise les exigences et objectifs des intervenants successifs du projet.
- CCAG :: Cahier des Clauses Administratives Générales	
- CCAP :: Cahier des Clauses Administratives Particulières	
- CCCG :: Cahier des Clauses Contractuelles Générales	
- CCTP :: Cahier des Clauses Techniques Particulières	
- Calepinage :: Assemblage d'éléments constructifs standards ou préfabriqués, sur la trame du bâtiment, et selon des règles de coordination dimensionnelle.
- Charte BIM :: Document prescrivant les modalités à respecter en terme de modélisation d’information et de modélisation graphique au sein d’un organisme.
- CVC :: Chauffage, Ventilation et Climatisation	
- CIS/2 :: CIMsteel Interation Standards
  :: Format standard pour échanger des données CAO de structures.
- CityGML :: City Geography Markup Language
  :: Standard de l'OGC (Open Geospatial Consortium). Il permet de décrire la représentation, le stockage et l'échange de modèles 3D de villes numériques et de modèles de terrains (géométrie, topologie, apparence, sémantique).
- CIM :: City Information Modeling
  :: Modélisation des Informations de la Ville.
- Classe :: Une classe regroupe des objets de même type, possédant des propriétés et un comportement semblable.
- Classification :: Processus de tri des objets intégrés à la maquette selon un standard, une norme ou une définition propriétaire.
- Closed BIM :: Echanges fermés, entre logiciels d’un même éditeur. Le Closed BIM est un procédé utilisé au sein du BIM. Lorsqu’elles collaborent selon une approche Closed BIM, toutes les parties utilisent le même logiciel. L’échange de modèles BIM ne nécessite dès lors pas de modifications de format de fichier.
- Cloud :: Stockage des données sur les serveurs accessibles par internet (publics ou privés). Ce système permet une externalisation des données, de leur stockage, de leur sauvegarde, avec des accès distants (y compris pour des utilisateurs de plusieurs sociétés différentes). Il permet donc le travail collaboratif par l’accès simultanée de plusieurs utilisateurs au même fichier.
- Codification :: Attribution d’un code à un fichier afin qu’il soit identifiable de façon unique dans le CDE ou dans la GED.
- CDE :: Common Data Environment
  :: Référentiel de données qui contient toutes les informations numérisées relatives à un projet (plateforme collaborative, logiciels, maquettes, modèles, contrats, correspondances, …). Source unique des informations numérisées pour un projet ou un ouvrage donné, utilisée pour collecter, gérer et diffuser chaque élément d’information via un processus géré et des outils adaptés.
- CRR :: Compte Rendu de Réunion
- CFD :: Computational Fluid Dynamics
  :: Technologie numérique permettant la simulation par élément fini des phénomènes de mécanique des fluides. (Écoulements, pertes de charges etc.) La simulation de la prise à l’air du bâtiment, la simulation des flux d’air en environnement ISO 8 ou encore la simulation de la circulation d’eau dans une pompe sont des exemples de CFD.
- CAD :: Computer Aided Design
- CAO :: Conception Assistée par Ordinateur
- CREM :: Conception Réalisation Exploitation Maintenance
- CONF :: Configuration
- Conflit :: Aussi appelé « Clash », Incident potentiel mis en lumière à la suite d’un contrôle des conflits (clash control).
- COBie :: Construction-Operations Building information exchange
  :: Référentiel de données qui contient toutes les informations numérisées relatives à un projet (plateforme collaborative, logiciels, maquettes, modèles, contrats, correspondances, …). Source unique des informations numérisées pour un projet ou un ouvrage donné, utilisée pour collecter, gérer et diffuser chaque élément d’information via un processus géré et des outils adaptés.
- Conteneur :: Ensemble nommé de données et d’informations au sein d’un fichier, d’un système ou d’une hiérarchie de stockage de applications. Il peut s’agir d’un répertoire, sous-répertoire, fichier de données (comme un modèle, un document, un tableau, un schéma…) ou d’un sous-ensemble distinct d’un fichier de données tel qu’un chapitre ou une section, une couche ou un symbole.
- CPE :: Contrôle Particulier d’Essais
- Convention BIM :: Document établissant la stratégie de développement du processus BIM d’un organisme.
- Coordinateur BIM :: Acteur référent qui gère la partie du projet spécifique traitée en BIM par son entité. Il forme les sous-traitants impliqués dans la génération de modèles numériques BIM, et participe à l’élaboration du PEB. Il pilote et audit également les modèles BIM selon les contrôles qualités définis par le PEB.Rôle BIM qui consiste à organiser et à contrôler la coordination globale entre les disciplines.Note : Le coordinateur BIM remplit souvent un rôle opérationnel global et travaille en étroite collaboration avec le BIM manager.
- Cycle de vie :: Le cycle de vie est la période s’étendant de la livraison/réception à la fin de vie, en passant par l’utilisation/le fonctionnement.
- DWF :: Design Web Format
  :: Format de fichier conçu et utilisé par l'éditeur Autodesk, permettant d'échanger des données vectorielles 2D et 3D d'une façon neutre et avec un poids de fichier réduit. Ce format peut être consulté à l'aide de viewers gratuits, et est également reconnu par de nombreux logiciels techniques. Il est utilisé essentiellement pour la consultation des données (visualiser un modèle 3D avec les informations associées aux éléments géométriques : calque de création, type, matériaux...) et permet l'annotation par un tiers (porter des remarques, questions...) avant de retourner le fichier à son créateur pour qu'il importe ces données dans son logiciel de création.
- DAO :: Dessin Assisté par Ordinateur	
- Détection des conflits :: Usage BIM qui permet de détecter les conflits ou les erreurs dans l’espace en comparant les modèles BIM (partiels) ou certains éléments de ces modèles.Les conflits mettent en lumière les défauts tels que des éléments se chevauchant, prévus en double ou insuffisamment espacés.Les conflits étant détectés directement dans le modèle BIM, les erreurs peuvent être évitées sur chantier, où elles sont souvent plus difficiles à résoudre et où elles entraînent des coûts supplémentaires ainsi qu’une perte de temps.
- DTH :: Dictionnaire Technique Harmonisé
  :: Il rassemble les caractéristiques (comprenant libellé, l'unité utilisée, le type de données, la longueur du champ, définition, l'usage, un identifiant unique...) permettant de décrire les performances d'un produit, les caractéristiques d’un objet, d’un ouvrage, d’un équipement ou d’un système constructif. Historiquement développé avec Edibatec et GS1, le standard de description SDC a été repris par l'AIMCC sous le vocable de DTH (Dictionnaire Technique Harmonisé) pour y introduire une approche horizontale des informations produits par domaine d’information et non plus une approche verticale par métier.
- dthX :: dictionnaire technique harmonisé eXchange
  :: Format de description des données produits et systèmes constructifs signifiant dictionnaire technique harmonisé eXchange.
- DIF :: Diffusé
  :: Attribut signalant l'état diffusé d'un livrable
- DMU :: Digital Mock-Up
  Maquette numérique
- Digital Twin :: En français : Jumeau numérique.
  :: Représentation numérisée d’un ouvrage physique, utilisée principalement pour les besoins de son exploitation et de sa maintenance.Le jumeau numérique évolue au fur et à mesure des modifications, des rénovations, de l’exploitation, de la maintenance de l’ouvrage réel.
- Dimension :: Direction d’expansion d’un objet dans l’espace.
- DAS :: Domaine d’Activité Spécifique	
- Donnée :: Informations brutes, non structurées.
- DCE :: Dossier de Consultation des Entreprises
- DOE :: Dossier des Ouvrages Exécutés
- DJD :: Dossier Justificatif Détaillé
- DWG :: DraWinG
  :: Format natif du logiciel AutoCAD de l’éditeur Autodesk, devenu standard de fait pour l’échange de données géométriques 2D et 3D entre logiciels graphiques.
- DXF :: Drawing eXchange Format
  :: Structure de communication entre le logiciel Autocad d’Autodesk, et tout autre logiciel doté d’une interface capable de lire ou écrire ce type de fichier neutre : devenu standard, de fait, d’échanges de dessin.
- ELE :: Electricité
- ERP :: Enterprise Ressource Planning
  Voir PGI
- ETMT :: Entreprise Titulaire d'un Marché de Travaux
- EIS :: Equipement Important pour la Sûreté
- ESQ :: Esquisse
- ERP :: Etablissement Recevant du Publique
- EBM :: Etude de Maturité BIM
- CEN :: European Committee for Standardization
  :: Organisme créé en 1961 afin d'harmoniser les normes élaborées en Europe. Son siège est situé à Bruxelles. Tous ses membres nationaux – qu'ils soient membres de plein droit, affiliés ou organismes de normalisation partenaires – sont également membres de l'Organisation internationale de normalisation (ISO).
- EIR :: Exchange information requirements
- EXE :: Exécution
- EXPRESS :: Langage formel normalisé pour décrire la structure de bases de données orientées objets. EXPRESS est un outil de STEP.
- EXPRESS-G :: Formalisme graphique pour décrire une structure de base de données. L’avantage d’EXPRESS-G est qu’il est un des outils de STEP, qui permet immédiatement d’obtenir une traduction de la base de données, en langage EXPRESS.
- XML :: eXtended Markup Langage
- FAO :: Fabrication Assistée par Ordinateur
- FED :: Fiche d'Evaluation de Document
- FII, FIE :: Fiche d’Interface
  :: Fiche descriptive d’une interface entre deux personnes. Le document porte l’intégralité de la résolution de l’interface. FII : Fiche d’interface interne, FIE : Fiche d’interface externe.
- FDC :: Fiche De Contrôle
  :: Fiches éditées lors du contrôle de chaque maquette numérique prévu par le BIM management.
- FDES :: Fiche de Déclarations Environnementales et Sanitaires :: Fiches de déclarations environnementales et sanitaires ; par une étude détaillée (selon la norme NF P01-010), elles permettent de réaliser un bilan environnemental des matériaux de construction pouvant être utilisés dans un projet afin de minimiser les impacts sur l’environnement et la santé.
- FDM :: Fiche De Modification
- FNC :: Fiche de Non Conformité
- FDS :: Fiche De Suivi
  :: Fiches éditées lors de l’édition de chaque maquette numérique pour en tracer les évolutions notables
- FQR :: Fiche Questions Réponses
- FTP :: File Transfer Protocole
  :: Protocole de communication destiné au partage de fichiers sur un réseau TCP/IP.Il permet, depuis un ordinateur, de copier des fichiers vers un autre ordinateur du réseau, ou encore de supprimer ou de modifier des fichiers sur cet ordinateur. Il permet de transférer des fichiers volumineux très rapidement.FTPS ou SFTP est la variante sécurisée par les protocoles de chiffrement SSL ou TLS.
- Format ouvert :: Un format de fichier est ouvert quand il permet d'être échangé entre plusieurs logiciels. Un format de fichier ouvert définit un protocole de communication, d'interconnexion ou d'échange et tout format de données interopérable et dont les spécifications techniques sont publiques et sans restriction d'accès ni de mise en œuvre.
- Format propriétaire :: Un format de fichier est propriétaire lorsqu'il caractérise un éditeur disposant d'une solution logicielle ou d'une gamme de solutions logicielles. Le format propriétaire est régi par les lois relatives au copyright et à la Trade mark (TM) et n'est généralement pas compatible avec d'autres formats propriétaires. Ces formats sont aussi appelés « format fermé », par opposition aux formats ouverts.
- GML :: Geography Markup Language
  :: Geography markup language - langage dérivé du XML pour encoder, manipuler et échanger des données géographiques. C'est un standard développé par l'Open Geospatial Consortium pour garantir l'interopérabilité des données dans le domaine de l'information géographique et de la géomatique
- GMAO :: Gestion de la Maintenance Assisté par Ordinateur
  Computer Aided Facility Management (CAFM)
- GED :: Gestion Electronique des Documents
- GEM :: Gestion Exploitation Maintenance
  :: Dit également Facility Management (FM) ou Operation & Maintenance (O&M)
- GUID :: Globally Unique Identifier
  :: Identifiant unique permettant la traçabilité d’un élément tout au long de son cycle de vie.
- gbXML :: Green Building XML
  :: Format utilisé pour faciliter le transfert des propriétés d'un bâtiment stockées dans un modèle 3D BIM vers les applications de calculs énergétiques
- HSD :: Hauteur Sous Dalle	
- HSFP :: Hauteur Sous Faux-Plafond	
- HVAC :: Heating, Ventilation & Air Conditionning	
- Héritage :: Mécanisme qui permet à des objets d'une sous-classe de bénéficier des propriétés des classes "parents" ou sur-classes. Critère principal de structuration des concepts.
- HSSE :: Hygiène, Santé, Sécurité et Environnement	
- BT :: Indice Bâtiment
  :: Indice de révision des prix pour les travaux de bâtiment.
- IFC :: Industry Foundation Classes
  :: Format d'échange ouvert de données géométriques et d'information normalisé par l'ISO 16739. Les IFC ont pour but d’assurer l’interopérabilité des logiciels métiers BIM.
- Information :: Données traitées qui sont placées dans un contexte, ce qui leur confère un sens et une structure, et les rend, de ce fait, exploitables.
- IDM :: Information Delivery Manual
  :: Méthode normée, développée par buildingSMART International, permettant de spécifier précisément les processus et les informations échangées entre les acteurs, à chaque étape d’un projet sur l’ensemble du cycle de vie d’un ouvrage. Les IDM sont définis par la norme ISO 29481-1 et ISO 29481-2.
- IDS :: Information Delivery Specifications
:: Document interprétable par ordinateur qui définit les exigences d'échange pour l'échange basé sur des modèles. Il définit la manière dont les objets, les classifications, les matériaux, les propriétés et même les valeurs doivent être livrés et échangés. Permet de valider les fichiers IFC au moyen d’analyses automatisées. C'est un composant central qui peut être utilisé comme contrat pour fournir les bonnes informations ("Modèle en tant que document légal"). Il a la capacité de créer des exigences localisées et spécifiques à l'utilisation pour vos projets et votre portefeuille d'actifs.
- IT :: Information Technology	
- Ingénierie concourante :: Selon la norme ISO 19101, il s’agit de la « capacité́ d’un système ou d’une composante d’un système à permettre un partage des informations ainsi qu’un contrôle des processus coopératifs ». L’Ingénierie concourante implique simultanément les différents acteurs dans toutes les phases du cycle de vie du projet.
- INB :: Installation Nucléaire de Base	
- INBS :: Installation Nucléaire de Base Secrète	
- IRSN :: Institut de Radioprotection et de Sûreté Nucléaire	
- ISO :: International Organization for Standardization
  :: Organisme de normalisation international composé de représentants d'organisations nationales de normalisation de 167 pays, selon le principe d’un membre par pays. L'ISO est le plus grand organisme de normalisation au monde et demeure une organisation non gouvernementale.
- Interopérabilité :: Capacité d’échanger par la présence d’un standard neutre et ouvert des données entre les différents « modèles » sans dépendre d’un acteur ou d’un outil en particulier.
- Jalon :: 
- KPI :: Key Performance Indicator	
- LIM :: Landscape Information Modeling
  :: Modélisation des Informations Paysagères
- LandXML :: Format d'échanges de données basé sur le XML, utilisé en génie civil et géomatique afin transmettre les données comme les axes de routes, surface de terrain, etc. La majorité des logiciels d'infrastructures supportent l'import/export de ce format
- LOD :: Level Of Definition
  voir NRD
- LoD :: Level Of Details
  Voir NRG
- LOI :: Level Of Information
  Voir NRI
- LOIN :: Level Of Information Need
  :: Cadre qui définit l’étendue et la granularité de l’information (Norme ISO 19 650). Ce cadre spécifie la manière de décrire un échange d’information et concerne à la fois l’information géométrique et non géométrique dont la documentation.
- LCA :: Life Cycle Assesment	
- LDA :: Liste des Documents Applicables
  :: Aperçu actualisé des documents contractuels tout au long du projet.
- LDE :: Liste des Documents d’Execution
  :: Aperçu actualisé des livrables tout au long du projet.
- LOFC :: Liste des Opérations de Fabrication et de Contrôle	
- LOMC :: Liste des Opérations de Montage et de Contrôle	
- Livrable 2D :: Ensemble des plans du projet livrés au client pour répondre à un jalon
- Livrable 3D :: Ensemble des maquettes numériques du projet livrées au client pour répondre à un jalon
- MCO :: Maintiens en Condition Opérationnelle
- MOE :: Maitrise d’Œuvre
  :: Est la personne qui va décider des moyens techniques mis en œuvre pour concevoir le produit conformément à ce qui a été défini par la MOA.
- MOEe :: Maitrise d’Œuvre d'ensemble
- MOEp :: Maitrise d’Œuvre particulière
- MOA :: Maitrise d’OuvrAge
- MN :: Maquette Numérique
  :: Modèle 3D servant de base partagée de données graphiques et alphanumériques.Représentation graphique de la base de données numérique, généralement en 3D, contenant des objets BIM (voir Objet BIM) portant l’ensemble des informations et des propriétés du projet.Cette maquette est réalisée à partir d’outils informatique BIM.Cette base de données peut être exploitée de différentes façons : représentation géométrique 3D, tableaux, nomenclatures d’objets.
- MPPE :: Marché de Partenariat de Performance Energétique	
- MGP :: Marché Global de Performance
- MGPE :: Marché Global de Performance Energétique
- MGS :: Marché Global Sectoriel
- MIDP :: Master Information Delivery Plan
- Maturité :: (Contributeurs) Niveau d'intégration du processus BIM par les intervenants d'un projet. (Projet) Niveau d'intégration du processus BIM dans le projet et de la qualité de réalisation des usages BIM. (Entreprise) Niveau d’intégration du processus BIM au sein d’une entreprise.
- MEP :: Mechanical, Electrical and Plumbing
  :: Concerne les réseaux énergétiques et fluidiques.
- MERISE :: Méthode d'Etude et de Réalisation Informatique pour les Systèmes d'Entreprise :: Méthode d'analyse, de conception et de gestion de projet informatique.
- MVD :: Model View Definition
  :: Définit un sous-ensemble du schéma IFC, nécessaire pour satisfaire à une ou plusieurs exigences d'échanges dans le secteur de l'AEC.
- MOB :: Modélisation des objets du bâtiment
  :: Recherche française axée sur les aspects de la modélisation conceptuelle lors de la phase de construction des ouvrages.Elle aborde l’exploitation dynamique du modèle, dans une problématique d’ingénierie concourante.
- NBDM :: Neutral Building Data Model
  :: Format d’échange entre logiciels de thermique, similaire à gbxml aux Etats-Unis.
- NRI :: Niveau Requis d'Information
  :: Réfère aux objectifs d'enrichissement en information des objets modélisés.
- NRD :: Niveau Requis de définitio
n :: Réfère aux objectifs d'information et de précision graphique des objets modélisés.
- NRG :: Niveau Requis de Géométrie
  :: Réfère à la granularité de la représentation géométrique des maquettes numériques qui sont attendues aux différents stades de projet et d’exploitation.
- Nuage de points :: Fichiers obtenus à partir d’un scanner laser 3D, reconstituant l’espace où le volume capté par l’appareil : ces points sont ensuite importés dans des logiciels graphiques, pour visualiser l’espace, prendre des mesures des dimensions, construire une maquette numérique de l’existant.
- Objectif BIM :: Expression des exigences de la MOA pour un projet BIM
- Objet BIM :: Objet de construction numérique. Représentation virtuelle d’un élément de construction, en trois dimensions, formellement identifié avec ses propriétés.
- Objet BIM Générique :: Objet décrivant, en termes de spécifications fonctionnelles et de performances, un ouvrage, une partie d’ouvrage ou un composant. Il est utilisé en phase conception jusqu’au marché de travaux pour préciser les exigences attendues dans les phases amont du développement de la maquette numérique et constitue ainsi l’amorce de l’objet représentatif de la solution pratique correspondante. Ces objets sont ensuite partagés, exploités par l’ensemble des acteurs tout au long du cycle de vie de l’ouvrage, qui renseigne, complète et détaille leurs paramètres.
- OmniClass :: Système américain de classification des produits de construction.
- Open BIM :: Approche open-source pour la conception, la réalisation et l'exploitation de bâtiment, en collaborations, basée sur des normes et des flux de travail ouverts. L’Open BIM s’appuie sur les structures standardisées des données, des inventaires et des règles d’échanges, telles que les normes ISO 16739, ISO 12006-3 et ISO 29481-1. Désigne l’interopérabilité pour le BIM. C’est la possibilité de pouvoir échanger des données entre logiciels BIM d’éditeurs différents, grâce à un standard d’échanges. La norme reconnue d’interopérabilité BIM est l’IFC, développés et maintenus par buildingSMART international.
- ODBC :: Open Database Connectivity
  :: Protocole qui permet à une application informatique de manipuler plusieurs bases de données qui sont mises à disposition par des systèmes de gestion de bases de données (SGBD) ayant chacun un procédé propre.
- OPC :: Ordonnancement Planification Coordination	
- OIR :: Organizational Information Requirements	
- Ouvrage :: Désigne un élément du bâtiment construit sur place, faisant appel à de la main d'œuvre et des matériaux.
- PEB :: Plan d’Execution BIM
  :: Document élaboré pour un projet donné par chaque entreprise décrivant les méthodes organisationnelles, la structuration des données, les représentations graphiques, la gestion et le transfert des données du projet, ainsi que les processus, les modèles, les utilisations et le rôle de chacun de ses intervenants dans l’environnement collaboratif BIM du projet. Il est la réponse au cahier des charges BIM du dossier de consultation des entreprises.
- PGI :: Plan de Gestion des Interfaces
- PMAQ :: Plan de Management et d’Assurance Qualité
- PTNB :: Plan de transition numérique dans le bâtiment
  :: (2015-2018) dirigé par B.Delcambre : 1er plan public français pour aider la filière bâtiment dans sa digitalisation.
- Plateforme collaborative :: C’est une infrastructure d’échange de données liées à un projet selon des méthodologies définies. Elle centralise tous les outils liés à la conduite de projet et la gestion des connaissances liées à ce même projet et les mets à disposition des acteurs dudit projet.
- PLB :: Plomberie
- PDF :: Portable Document Format
:: Le PDF est un format enveloppe, pouvant contenir de nombreux types de données : textes, dessins bitmap, dessin vectoriel 2D, dessin vectoriel 3D. Il est utilisé pour produire des documents et dossiers graphiques dont l'affichage est conforme au document initial sur tout système (Mac, Windows, Linux, Unix, iOS, Android...), et l'impression identique à celle produite depuis le logiciel d'origine. Le format PDF comprime fortement les données, sans altération, et produit donc des fichiers de poids très léger.
- Pré-Programme
- PV :: Procès Verbal
- PVC :: Procès Verbal de Contrôle
- PVCF :: Procès Verbal de Contrôle - Fabrication
- PVCM :: Procès Verbal de Contrôle - Montage
- Processus BIM :: Ensemble de processus d’application opérationnelle de cas d’usages BIM. Un processus est un ensemble d’opérations, d’actions ou d’évènements mis en œuvre pour atteindre un ou plusieurs objectifs et réaliser un usage BIM. Les processus sont généralement illustrés par des représentations graphiques telles que des logigrammes ou des schémas BPMN.
- PCI :: Processus de Conception Intégrée
  :: Approche de travail pour concevoir un projet ou un produit – de sa conception à sa mise à disposition intégrant la définition du produit, les processus de fabrication, et tous les autres processus requis dans le cycle de vie tels que, notamment, le fonctionnement (dans des environnements mécaniques, thermiques, acoustiques, électromagnétiques…) ou la maintenance. Selon la norme ISO 19101, il s’agit de la « capacité́ d’un système ou d’une composante d’un système à permettre un partage des informations ainsi qu’un contrôle des processus coopératifs ».
- PIM :: Product Information Modeling
  :: (industrie)
- PLM :: Product Life cycle Management
  :: Outil permettant de gérer la collection des fichiers contenant les paquets d’objets des différents acteurs et de gérer l’accès à ces fichiers dans le temps et suivant le respect des propriétés de chaque acteur.
- PPBIM :: Product Properties BIM
  :: La norme expérimentale AFNOR XP P07-150 dite norme PPBIM concerne les propriétés des produits et systèmes (ensembles de produits respectant des règles d’assemblage et/ou de mise en oeuvre) utilisés en construction. Elle porte sur l’harmonisation des dictionnaires de propriétés, de groupes de propriétés (ensembles de propriétés permettant d’organiser les propriétés par thèmes), de documents, de produits, d’objets BIM génériques et de systèmes constructifs dans le cadre d’une maquette numérique. Est devenue PR EN ISO 23386.
- PGI :: Progiciel de Gestion Intégré :: Progiciel qui permet de gérer l’ensemble des processus opérationnels d’une entreprise en intégrant plusieurs fonctions de gestion
- PRE :: Programme de Rénovation Energétique	
- PGE :: Programme Général d’Essais
- PPE :: Programme Particulier d’Essais
- PTD :: Programme Technique Détaillé
- PTF :: Programme Technique Fonctionnel
- PIM :: Project Information Model (bâtiment)
- PIR :: Project Information Requirements
- PRO :: Projet
- Propriété :: Attribut qui qualifie les caractéristiques graphiques, physique, analytique et techniques d’un objet. Caractéristique ou qualité d’un élément de construction.  ISO 6707-1 (3.7.1.3) : “Caractéristique ou qualité d’un objet.”
- Protocole BIM :: Document qui définit les axes principaux du processus BIM d’un organisme. Il regroupe un ensemble de règles, de procédures et de modalités organisationnelles à respecte. Il peut servir de socle pour l’élaboration du PEB.
- PAS :: Publicly Avaible Specification :: Statut intermédiaire des standards ISO, avant de devenir IS (International standard)
- QSE :: Qualité, Sécurité, Environnement	
- RICT :: Rapport Initial de Contrôle Technique	
- Relation :: Lien formel entre deux objets de même classe ou de classe différentes. Une relation est aussi un objet.
- RSV :: Réservation
- Réservation :: Élément représentant une ouverture ou un forage à prévoir dans un autre élément. Généralement l’emplacement prévu pour le passage d’une installation ou d’une conduite technique.
- RACI :: Responsible, Accountable, Consulted, Informed
  :: Description générique des rôles des intervenants dans un projet. Est généralement utilisé à travers une matrice dite « Matrice RACI » et est utilisé pour identifier les responsabilités de chacun.
- RIM :: Ressource Information Modeling
  :: Modélisation des Informations de Déconstruction
- RVT :: Format des fichiers de projet natif du logiciel Revit.
- RFA :: Revit Family
  :: Format des fichiers d’objet BIM natif du logiciel Revit.Fichier de standardisation de la modélisation et pouvant être partagé aux différents modeleurs BIM utilisant le logiciel Revit pour qu’ils puissent travailler sur une base commune.
- RTE :: Revit Template
  :: Format des fichiers de gabarit natif du logiciel Revit.
- RIBA :: Royal Institute of British Architects
- SST :: Santé et Sécurité au Travail
- SDI :: Schéma Directeur Immobilier
- PYRO :: Sécurité Pyrotechnique
- Smart Contracts :: Les smart contracts sont des protocoles informatiques qui facilitent, vérifient et exécutent la négociation ou l'exécution d'un contrat, ou qui rendent une clause contractuelle inutile (car rattachée au contrat intelligent). Ils ont généralement une interface utilisateur et émulent la logique des clauses contractuelles. Il s’agit de code informatique, et si l'interface utilisateur venait à disparaître, il serait toujours possible d'interagir avec ceux-ci2. Seul un arrêt du réseau sur lequel les contrats intelligents sont hébergés pourrait les rendre inaccessibles.
- SaaS :: Software as a Service :: Application logicielle en ligne, sur Internet, ne nécessitant pas d'installation sur le poste client.
- SLI :: Soutiens Logistique Intégré	
- SMAQ :: Spécification de Management et d’Assurance Qualité	
- STEP :: STandard for the Exchange of Product data model
  :: Format normalisé (ISO 10303) de modèle d'information des produits industriels
- SAMP :: Strategic Asset Management Plan	
- STR :: Structure	
- SADT :: Structured Analysis and Design Technique
  :: Démarche systémique de modélisation d'un système complexe ou d'un processus opératoire.
- SQL :: Structured Query Language
  :: Langage informatique normalisé (ISO/CEI 9075) servant à exploiter des bases de données relationnelles. La partie langage de manipulation des données de SQL permet de rechercher, d'ajouter, de modifier ou de supprimer des données dans les bases de données relationnelles.
- SDF :: Sûreté De Fonctionnement
- SN :: Sûreté Nucléaire
- SDO :: Surface Dans Œuvre
- SDP :: Surface de Plancher
- SHOB :: Surface Hors Œuvre Brute
- SHON :: Surface Hors Œuvre Nette
- SU :: Surface Utile
  :: La surface utile est la surface intérieure des locaux d’activité. Les circulations et les locaux techniques n’entrent pas dans le calcul de la surface utile.
- SAE :: Système d’Alimentation Electrique
- SEL :: Système d’Etanchéité Liquide
- SI  :: Système d’Information
  :: (Informatique) Ensemble organisé de ressources qui permet de collecter, stocker, traiter et distribuer de l'information1, en général grâce à un réseau d'ordinateurs.
- SIG :: Système d’Information Géographique
- SGDB, DBMS :: Système de Gestion de Base de Données
- SMQ :: Système de Management de la Qualité
- SMI :: Système de Management Intégré
- SSI :: Système de Sécurité des Informations
- SSI :: Système de Sécurité Incendie
- Unité SI :: Unités du Système International
- TIDP :: Task Information Delivery Plan
- TQC :: Tel Que Construit
- TDC :: Toutes Dépenses Confondues
- TTC :: Toutes Taxes Comprises
- VRD :: Voiries et Réseaux Divers
- WIP :: Work In Progress
- X-REF :: Référence externe
- Référence externe :: Mécanisme qui permet de référencer un autre fichier CAO, depuis un fichier CAO maître.
- Surmodélisation :: Fait de livrer plus d’informations que nécessaire dans un modèle BIM. La surmodélisation constitue une forme de gaspillage. Elle implique non seulement un surcroît d’effort pour la partie qui fournit l’information, mais aussi un allongement des délais de traitement et une augmentation des coûts de stockage. Elle entrave en outre l’obtention des informations souhaitées. Des conventions appropriées en matière de livraison d’informations et de modélisation permettent d’éviter ce problème.
- Système d'Information Géographique :: Système informatique permettant, à partir de diverses sources, de rassembler et d'organiser, de gérer, d'analyser et de combiner, d'élaborer et de présenter des informations localisées géographiquement, contribuant notamment à la gestion de l'espace. (Société française de photogrammétrie et télédétection, 1989). Les logiciels de SIG sont des SGBD Spatiales.
- Système Internationnal :: La norme internationale ISO 80000-1:2009 décrit les unités du Système international et les recommandations pour l’emploi de leurs multiples et de certaines autres unités.
- Uniclass :: Système de classification des produits de construction utilisé au Royaume-Uni
- Usage BIM :: Technique ou méthode mise en œuvre en vue de réaliser un certain objectif BIM. Un usage BIM est une explicitation de processus métiers intégrant des pratiques BIM, c’est-à-dire la description d’un processus concret tel qu’il sera mis en œuvre sur un projet. Cela permet de décrire factuellement les usages voulus des maquettes numériques, les interactions des différents acteurs avec cette base de données, pour des actions métiers précises allant de la production d’images jusqu’à l’exploitation de bâtiment.
- Version :: État d’un document ou d’un ﬁchier à la suite d’une légère modiﬁcation apportée à un ﬁchier ou à un document.  Note: Une révision peut comprendre plusieurs versions d’un modèle BIM.
- Viewer :: Logiciel utilitaire, souvent gratuit, permettant d’afficher, visualiser, manipuler un fichier lorsqu’on ne dispose pas de son logiciel d’origine.
- Voieries et Réseaux Divers :: Concerne un ensemble de travaux nécessaires pour aménager un espace ou construire un bâtiment, et le raccorder aux différents réseaux existants.  Ces travaux désignent non seulement le raccord d’un bâtiment aux différents réseaux (électricité, eau, etc.), mais aussi les travaux d’embellissement qui visent à rendre ces réseaux invisibles à l’œil nu (notamment en enfouissant les tuyaux sous terre, par le moyen d’un terrassement du terrain).
